apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: gmiskos
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 60000       # 1 minute retention time
    segment.bytes: 10485760   # 10 MB segment size
