apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: apk-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 3600000
    segment.bytes: 524288000