apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: gmiskos
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 5Gi
          deleteClaim: false
          persistentVolumeClaim:
            claimName: kafka-data-0  # Specify the name of the PVC here
        - id: 1
          type: persistent-claim
          size: 5Gi
          deleteClaim: false
          persistentVolumeClaim:
            claimName: kafka-data-1  # Specify the name of the PVC here
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
      persistentVolumeClaim:
        claimName: zookeeper-data  # Specify the name of the PVC here
  entityOperator:
    topicOperator: {}
    userOperator: {}