apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: gmiskos
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    storage:
      type: jbod
      volumes:
        - id: 0
          type: ephemeral
          size: 2Gi  # Adjust the size if needed
          deleteClaim: true  # Set deleteClaim to true for ephemeral storage
        - id: 1
          type: ephemeral
          size: 2Gi  # Adjust the size if needed
          deleteClaim: true  # Set deleteClaim to true for ephemeral storage
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
      size: 2Gi  # Adjust the size if needed
      deleteClaim: true  # Set deleteClaim to true for ephemeral storage
  entityOperator:
    topicOperator: {}
    userOperator: {}